# -*- coding: utf-8 -*-
"""Pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11kfB5SQLkLisCG0bF4R51xYgotbhi6p1
"""

"""
STEP 1: Data Cleaning and Preprocessing
ANN Retail Sales Forecasting Project (PyTorch)
"""

import pandas as pd
import numpy as np
import os

sales_df    = pd.read_csv("sales_data_set.csv")
features_df = pd.read_csv("Features_data_set.csv")
stores_df   = pd.read_csv("stores_data_set.csv")

print(f"Sales shape    : {sales_df.shape}")
print(f"Features shape : {features_df.shape}")
print(f"Stores shape   : {stores_df.shape}")

# ── 2. Convert Date Columns ────────────────────────────────────────────────────
for df in [sales_df, features_df]:
    df["Date"] = pd.to_datetime(df["Date"], dayfirst=True)

# ── 3. Merge All Three DataFrames ─────────────────────────────────────────────
df = sales_df.merge(features_df, on=["Store", "Date", "IsHoliday"], how="left")
df = df.merge(stores_df, on="Store", how="left")

print(f"\nMerged shape: {df.shape}")
print(df.head(3))

# ── 4. Handle Missing Values ───────────────────────────────────────────────────
print("\nMissing values before treatment:")
print(df.isnull().sum())

# MarkDown columns: fill NA with 0 (no markdown event)
markdown_cols = ["MarkDown1", "MarkDown2", "MarkDown3", "MarkDown4", "MarkDown5"]
df[markdown_cols] = df[markdown_cols].fillna(0)

# CPI and Unemployment: forward-fill within each store
df = df.sort_values(["Store", "Dept", "Date"])
df["CPI"]          = df.groupby("Store")["CPI"].transform(lambda x: x.ffill().bfill())
df["Unemployment"] = df.groupby("Store")["Unemployment"].transform(lambda x: x.ffill().bfill())

print("\nMissing values after treatment:")
print(df.isnull().sum())

# ── 5. Remove Negative Weekly_Sales (returns/errors) ──────────────────────────
neg_mask = df["Weekly_Sales"] < 0
print(f"\nNegative sales rows removed: {neg_mask.sum()}")
df = df[~neg_mask].reset_index(drop=True)

# ── 6. Data Types ─────────────────────────────────────────────────────────────
df["IsHoliday"] = df["IsHoliday"].astype(int)
df["Type"]      = df["Type"].map({"A": 0, "B": 1, "C": 2})   # label-encode store type

# ── 7. Save Cleaned Data ───────────────────────────────────────────────────────
os.makedirs("data", exist_ok=True)
df.to_csv("data/cleaned_data.csv", index=False)
print(f"\nCleaned data saved → data/cleaned_data.csv  |  Shape: {df.shape}")
print("\nColumn dtypes:\n", df.dtypes)

"""
STEP 2: Exploratory Data Analysis (EDA)
ANN Retail Sales Forecasting Project (PyTorch)
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

os.makedirs("outputs/eda", exist_ok=True)

df = pd.read_csv("data/cleaned_data.csv", parse_dates=["Date"])

# ── 1. Basic Statistics ────────────────────────────────────────────────────────
print("=== Basic Statistics ===")
print(df.describe())

# ── 2. Weekly Sales Distribution ──────────────────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(14, 5))
axes[0].hist(df["Weekly_Sales"], bins=80, color="steelblue", edgecolor="k")
axes[0].set_title("Weekly Sales Distribution")
axes[0].set_xlabel("Weekly Sales ($)")
axes[0].set_ylabel("Frequency")

axes[1].hist(np.log1p(df["Weekly_Sales"]), bins=80, color="coral", edgecolor="k")
axes[1].set_title("Log-Transformed Weekly Sales")
axes[1].set_xlabel("log(Weekly Sales + 1)")
plt.tight_layout()
plt.savefig("outputs/eda/01_sales_distribution.png", dpi=150)
plt.close()
print("Saved: 01_sales_distribution.png")

# ── 3. Sales Over Time ────────────────────────────────────────────────────────
monthly = df.groupby(df["Date"].dt.to_period("M"))["Weekly_Sales"].mean().reset_index()
monthly["Date"] = monthly["Date"].dt.to_timestamp()

plt.figure(figsize=(14, 5))
plt.plot(monthly["Date"], monthly["Weekly_Sales"], marker="o", linewidth=1.5, color="teal")
plt.title("Average Weekly Sales Over Time")
plt.xlabel("Date")
plt.ylabel("Avg Weekly Sales ($)")
plt.grid(alpha=0.3)
plt.tight_layout()
plt.savefig("outputs/eda/02_sales_over_time.png", dpi=150)
plt.close()
print("Saved: 02_sales_over_time.png")

# ── 4. Holiday vs Non-Holiday Sales ───────────────────────────────────────────
holiday_stats = df.groupby("IsHoliday")["Weekly_Sales"].mean()
print("\nAvg Sales — Non-Holiday:", round(holiday_stats[0], 2),
      "  Holiday:", round(holiday_stats[1], 2))

plt.figure(figsize=(7, 5))
holiday_stats.plot(kind="bar", color=["steelblue", "tomato"], edgecolor="k")
plt.xticks([0, 1], ["Non-Holiday", "Holiday"], rotation=0)
plt.title("Average Weekly Sales: Holiday vs Non-Holiday")
plt.ylabel("Avg Weekly Sales ($)")
plt.tight_layout()
plt.savefig("outputs/eda/03_holiday_vs_nonholiday.png", dpi=150)
plt.close()
print("Saved: 03_holiday_vs_nonholiday.png")

# ── 5. Sales by Store Type ────────────────────────────────────────────────────
type_map = {0: "A", 1: "B", 2: "C"}
df["Type_Label"] = df["Type"].map(type_map)
type_sales = df.groupby("Type_Label")["Weekly_Sales"].mean()

plt.figure(figsize=(7, 5))
type_sales.plot(kind="bar", color=["#4c72b0", "#dd8452", "#55a868"], edgecolor="k")
plt.title("Average Weekly Sales by Store Type")
plt.ylabel("Avg Weekly Sales ($)")
plt.xticks(rotation=0)
plt.tight_layout()
plt.savefig("outputs/eda/04_sales_by_store_type.png", dpi=150)
plt.close()
print("Saved: 04_sales_by_store_type.png")

# ── 6. Top 10 Departments by Sales ───────────────────────────────────────────
top_depts = df.groupby("Dept")["Weekly_Sales"].mean().nlargest(10)

plt.figure(figsize=(10, 5))
top_depts.plot(kind="bar", color="mediumpurple", edgecolor="k")
plt.title("Top 10 Departments by Avg Weekly Sales")
plt.xlabel("Department")
plt.ylabel("Avg Weekly Sales ($)")
plt.tight_layout()
plt.savefig("outputs/eda/05_top10_departments.png", dpi=150)
plt.close()
print("Saved: 05_top10_departments.png")

# ── 7. Correlation Heatmap ────────────────────────────────────────────────────
num_cols = ["Weekly_Sales", "Temperature", "Fuel_Price",
            "MarkDown1", "MarkDown2", "MarkDown3", "MarkDown4", "MarkDown5",
            "CPI", "Unemployment", "Size", "IsHoliday"]
corr = df[num_cols].corr()

plt.figure(figsize=(12, 9))
sns.heatmap(corr, annot=True, fmt=".2f", cmap="coolwarm", linewidths=0.5)
plt.title("Feature Correlation Heatmap")
plt.tight_layout()
plt.savefig("outputs/eda/06_correlation_heatmap.png", dpi=150)
plt.close()
print("Saved: 06_correlation_heatmap.png")

# ── 8. Markdown Impact on Holiday Sales ───────────────────────────────────────
holiday_df = df[df["IsHoliday"] == 1].copy()
total_md = holiday_df[["MarkDown1","MarkDown2","MarkDown3","MarkDown4","MarkDown5"]].sum(axis=1)
holiday_df["TotalMarkdown"] = total_md

plt.figure(figsize=(8, 5))
plt.scatter(holiday_df["TotalMarkdown"], holiday_df["Weekly_Sales"],
            alpha=0.3, color="darkorange", s=10)
plt.title("Total Markdown vs Weekly Sales (Holiday Weeks)")
plt.xlabel("Total Markdown ($)")
plt.ylabel("Weekly Sales ($)")
plt.tight_layout()
plt.savefig("outputs/eda/07_markdown_vs_sales_holiday.png", dpi=150)
plt.close()
print("Saved: 07_markdown_vs_sales_holiday.png")

print("\nEDA complete. All charts saved in outputs/eda/")

"""
STEP 3: Feature Engineering
ANN Retail Sales Forecasting Project (PyTorch)
"""

import pandas as pd
import numpy as np
import os

df = pd.read_csv("data/cleaned_data.csv", parse_dates=["Date"])
df = df.sort_values(["Store", "Dept", "Date"]).reset_index(drop=True)

# ── 1. Date / Calendar Features ───────────────────────────────────────────────
df["Week"]        = df["Date"].dt.isocalendar().week.astype(int)
df["Month"]       = df["Date"].dt.month
df["Quarter"]     = df["Date"].dt.quarter
df["Year"]        = df["Date"].dt.year
df["DayOfYear"]   = df["Date"].dt.dayofyear

# Cyclical encoding for Week and Month (avoids ordinal jump 52→1 / 12→1)
df["Week_sin"]    = np.sin(2 * np.pi * df["Week"]  / 52)
df["Week_cos"]    = np.cos(2 * np.pi * df["Week"]  / 52)
df["Month_sin"]   = np.sin(2 * np.pi * df["Month"] / 12)
df["Month_cos"]   = np.cos(2 * np.pi * df["Month"] / 12)

# ── 2. Lag Features (sales of previous weeks for same Store+Dept) ──────────────
grp = df.groupby(["Store", "Dept"])["Weekly_Sales"]
for lag in [1, 2, 4, 8, 13, 26, 52]:
    df[f"Sales_Lag_{lag}"] = grp.shift(lag)

# ── 3. Rolling Window Features ────────────────────────────────────────────────
for window in [4, 8, 13]:
    df[f"Sales_RollMean_{window}"] = (
        grp.shift(1)
           .transform(lambda x: x.rolling(window, min_periods=1).mean())
    )
    df[f"Sales_RollStd_{window}"] = (
        grp.shift(1)
           .transform(lambda x: x.rolling(window, min_periods=1).std().fillna(0))
    )

# ── 4. Total Markdown Feature ─────────────────────────────────────────────────
md_cols = ["MarkDown1", "MarkDown2", "MarkDown3", "MarkDown4", "MarkDown5"]
df["TotalMarkdown"]          = df[md_cols].sum(axis=1)
df["AnyMarkdown"]            = (df["TotalMarkdown"] > 0).astype(int)

# ── 5. Markdown × Holiday Interaction ─────────────────────────────────────────
df["Markdown_x_Holiday"]     = df["TotalMarkdown"] * df["IsHoliday"]

# ── 6. Store Size Buckets ─────────────────────────────────────────────────────
df["SizeBucket"] = pd.qcut(df["Size"], q=3, labels=[0, 1, 2]).astype(int)

# ── 7. Drop Rows with NaN Lags (initial rows per group) ───────────────────────
lag_cols = [c for c in df.columns if "Lag" in c or "Roll" in c]
before = len(df)
df = df.dropna(subset=lag_cols).reset_index(drop=True)
print(f"Rows before lag-dropna: {before}  →  after: {len(df)}")

# ── 8. Save ───────────────────────────────────────────────────────────────────
os.makedirs("data", exist_ok=True)
df.to_csv("data/featured_data.csv", index=False)
print(f"\nFeature-engineered data saved → data/featured_data.csv")
print(f"Total features: {df.shape[1]}  |  Rows: {df.shape[0]}")
print("\nColumns:\n", df.columns.tolist())

"""
STEP 4: ANN Model Training & Evaluation  —  PyTorch
ANN Retail Sales Forecasting Project
"""

import pandas as pd
import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import matplotlib.pyplot as plt
import joblib
import os

os.makedirs("models", exist_ok=True)
os.makedirs("outputs/evaluation", exist_ok=True)

# ── Reproducibility ────────────────────────────────────────────────────────────
SEED = 42
torch.manual_seed(SEED)
np.random.seed(SEED)
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {DEVICE}")

# ── 1. Load Data ───────────────────────────────────────────────────────────────
df = pd.read_csv("data/featured_data.csv", parse_dates=["Date"])

FEATURE_COLS = [
    "Store", "Dept", "Type", "Size", "SizeBucket",
    "IsHoliday", "Week", "Month", "Quarter", "Year", "DayOfYear",
    "Week_sin", "Week_cos", "Month_sin", "Month_cos",
    "Temperature", "Fuel_Price", "CPI", "Unemployment",
    "MarkDown1", "MarkDown2", "MarkDown3", "MarkDown4", "MarkDown5",
    "TotalMarkdown", "AnyMarkdown", "Markdown_x_Holiday",
    "Sales_Lag_1", "Sales_Lag_2", "Sales_Lag_4", "Sales_Lag_8",
    "Sales_Lag_13", "Sales_Lag_26", "Sales_Lag_52",
    "Sales_RollMean_4", "Sales_RollMean_8", "Sales_RollMean_13",
    "Sales_RollStd_4", "Sales_RollStd_8", "Sales_RollStd_13",
]
TARGET = "Weekly_Sales"

# ── 2. Train / Test Split (time-based) ────────────────────────────────────────
split_date = "2012-07-01"
train_df = df[df["Date"] < split_date]
test_df  = df[df["Date"] >= split_date]
print(f"Train: {len(train_df):,}  |  Test: {len(test_df):,}")

X_train = train_df[FEATURE_COLS].values.astype(np.float32)
y_train = train_df[TARGET].values.astype(np.float32)
X_test  = test_df[FEATURE_COLS].values.astype(np.float32)
y_test  = test_df[TARGET].values.astype(np.float32)

# ── 3. Scaling ─────────────────────────────────────────────────────────────────
scaler_X = StandardScaler()
scaler_y = StandardScaler()

X_train = scaler_X.fit_transform(X_train)
X_test  = scaler_X.transform(X_test)
y_train_scaled = scaler_y.fit_transform(y_train.reshape(-1, 1)).ravel()
y_test_scaled  = scaler_y.transform(y_test.reshape(-1, 1)).ravel()

joblib.dump(scaler_X, "models/scaler_X.pkl")
joblib.dump(scaler_y, "models/scaler_y.pkl")

# ── 3. Scaling ─────────────────────────────────────────────────────────────────
scaler_X = StandardScaler()
scaler_y = StandardScaler()

X_train = scaler_X.fit_transform(X_train)
X_test  = scaler_X.transform(X_test)
y_train_scaled = scaler_y.fit_transform(y_train.reshape(-1, 1)).ravel()
y_test_scaled  = scaler_y.transform(y_test.reshape(-1, 1)).ravel()

joblib.dump(scaler_X, "models/scaler_X.pkl")
joblib.dump(scaler_y, "models/scaler_y.pkl")

# ── 4. PyTorch Dataset ─────────────────────────────────────────────────────────
class SalesDataset(Dataset):
    def __init__(self, X, y):
        self.X = torch.tensor(X, dtype=torch.float32)
        self.y = torch.tensor(y, dtype=torch.float32).unsqueeze(1)

    def __len__(self):
        return len(self.X)

    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]

BATCH_SIZE = 512
train_loader = DataLoader(SalesDataset(X_train, y_train_scaled),
                          batch_size=BATCH_SIZE, shuffle=True)
test_loader  = DataLoader(SalesDataset(X_test,  y_test_scaled),
                          batch_size=BATCH_SIZE, shuffle=False)

# ── 5. ANN Architecture ────────────────────────────────────────────────────────
class SalesANN(nn.Module):
    """
    Deep ANN with:
      - 4 hidden layers (512 → 256 → 128 → 64)
      - BatchNorm + Dropout for regularization
      - ReLU activations
    """
    def __init__(self, input_dim):
        super().__init__()
        self.net = nn.Sequential(
            # Layer 1
            nn.Linear(input_dim, 512),
            nn.BatchNorm1d(512),
            nn.ReLU(),
            nn.Dropout(0.3),
            # Layer 2
            nn.Linear(512, 256),
            nn.BatchNorm1d(256),
            nn.ReLU(),
            nn.Dropout(0.3),
            # Layer 3
            nn.Linear(256, 128),
            nn.BatchNorm1d(128),
            nn.ReLU(),
            nn.Dropout(0.2),
            # Layer 4
            nn.Linear(128, 64),
            nn.BatchNorm1d(64),
            nn.ReLU(),
            nn.Dropout(0.1),
            # Output
            nn.Linear(64, 1),
        )

    def forward(self, x):
        return self.net(x)

model = SalesANN(input_dim=X_train.shape[1]).to(DEVICE)
print(f"\nModel:\n{model}")
total_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(f"Trainable parameters: {total_params:,}")

# ── 6. Loss, Optimizer, Scheduler ─────────────────────────────────────────────
criterion = nn.HuberLoss(delta=1.0)          # robust to outliers
optimizer = torch.optim.AdamW(model.parameters(), lr=1e-3, weight_decay=1e-4)
scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
    optimizer, mode="min", patience=5, factor=0.5
)

# ── 7. Training Loop ───────────────────────────────────────────────────────────
EPOCHS = 80
PATIENCE = 10

train_losses, val_losses = [], []
best_val_loss = float("inf")
patience_counter = 0

for epoch in range(1, EPOCHS + 1):
    # -- Train
    model.train()
    running_loss = 0.0
    for X_batch, y_batch in train_loader:
        X_batch, y_batch = X_batch.to(DEVICE), y_batch.to(DEVICE)
        optimizer.zero_grad()
        preds = model(X_batch)
        loss  = criterion(preds, y_batch)
        loss.backward()
        nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
        optimizer.step()
        running_loss += loss.item() * len(X_batch)

    train_loss = running_loss / len(train_loader.dataset)

    # -- Validate
    model.eval()
    val_running = 0.0
    with torch.no_grad():
        for X_batch, y_batch in test_loader:
            X_batch, y_batch = X_batch.to(DEVICE), y_batch.to(DEVICE)
            preds = model(X_batch)
            val_running += criterion(preds, y_batch).item() * len(X_batch)

    val_loss = val_running / len(test_loader.dataset)
    scheduler.step(val_loss)

    train_losses.append(train_loss)
    val_losses.append(val_loss)

    if epoch % 10 == 0 or epoch == 1:
        print(f"Epoch {epoch:3d}/{EPOCHS}  |  Train Loss: {train_loss:.5f}  |  Val Loss: {val_loss:.5f}")

    # -- Early Stopping
    if val_loss < best_val_loss:
        best_val_loss = val_loss
        patience_counter = 0
        torch.save(model.state_dict(), "models/best_ann_model.pt")
    else:
        patience_counter += 1
        if patience_counter >= PATIENCE:
            print(f"\nEarly stopping at epoch {epoch}")
            break

# ── 8. Load Best Model & Predict ──────────────────────────────────────────────
model.load_state_dict(torch.load("models/best_ann_model.pt", map_location=DEVICE))
model.eval()

all_preds, all_true = [], []
with torch.no_grad():
    for X_batch, y_batch in test_loader:
        preds = model(X_batch.to(DEVICE)).cpu().numpy()
        all_preds.extend(preds)
        all_true.extend(y_batch.numpy())

# Inverse-transform to original scale
y_pred_orig = scaler_y.inverse_transform(
    np.array(all_preds).reshape(-1, 1)).ravel()
y_true_orig = scaler_y.inverse_transform(
    np.array(all_true).reshape(-1, 1)).ravel()

# ── 9. Evaluation Metrics ──────────────────────────────────────────────────────
mae  = mean_absolute_error(y_true_orig, y_pred_orig)
mse  = mean_squared_error(y_true_orig, y_pred_orig)
rmse = np.sqrt(mse)
r2   = r2_score(y_true_orig, y_pred_orig)

print("\n" + "="*50)
print("  OVERALL MODEL EVALUATION (Test Set)")
print("="*50)
print(f"  MAE  : ${mae:,.2f}")
print(f"  MSE  : {mse:,.2f}")
print(f"  RMSE : ${rmse:,.2f}")
print(f"  R²   : {r2:.4f}")
print("="*50)

# ── 10. Holiday vs Non-Holiday Performance ────────────────────────────────────
test_results = test_df[["Date", "Store", "Dept", "IsHoliday", "Weekly_Sales"]].copy()
test_results["Predicted_Sales"] = y_pred_orig

holiday_res    = test_results[test_results["IsHoliday"] == 1]
nonholiday_res = test_results[test_results["IsHoliday"] == 0]

def print_metrics(name, true, pred):
    print(f"\n  [{name}]")
    print(f"    MAE  : ${mean_absolute_error(true, pred):,.2f}")
    print(f"    RMSE : ${np.sqrt(mean_squared_error(true, pred)):,.2f}")
    print(f"    R²   : {r2_score(true, pred):.4f}")

print("\n--- Holiday Breakdown ---")
print_metrics("Holiday Weeks",
              holiday_res["Weekly_Sales"], holiday_res["Predicted_Sales"])
print_metrics("Non-Holiday Weeks",
              nonholiday_res["Weekly_Sales"], nonholiday_res["Predicted_Sales"])

#── 11. Save predictions ───────────────────────────────────────────────────────
test_results.to_csv("outputs/evaluation/test_predictions.csv", index=False)

# ── 12. Plots ─────────────────────────────────────────────────────────────────
# Training curve
plt.figure(figsize=(10, 4))
plt.plot(train_losses, label="Train Loss")
plt.plot(val_losses,   label="Val Loss")
plt.xlabel("Epoch")
plt.ylabel("Huber Loss")
plt.title("Training vs Validation Loss")
plt.legend()
plt.tight_layout()
plt.savefig("outputs/evaluation/training_curve.png", dpi=150)
plt.close()

# Actual vs Predicted (sample 2000 points for clarity)
sample = test_results.sample(2000, random_state=42)
plt.figure(figsize=(8, 6))
plt.scatter(sample["Weekly_Sales"], sample["Predicted_Sales"],
            alpha=0.3, s=8, color="teal")
max_val = max(sample["Weekly_Sales"].max(), sample["Predicted_Sales"].max())
plt.plot([0, max_val], [0, max_val], "r--", linewidth=1.5, label="Perfect fit")
plt.xlabel("Actual Sales ($)")
plt.ylabel("Predicted Sales ($)")
plt.title("Actual vs Predicted Weekly Sales")
plt.legend()
plt.tight_layout()
plt.savefig("outputs/evaluation/actual_vs_predicted.png", dpi=150)
plt.close()

# Residuals
residuals = y_true_orig - y_pred_orig
plt.figure(figsize=(10, 4))
plt.hist(residuals, bins=100, color="mediumpurple", edgecolor="k")
plt.axvline(0, color="red", linestyle="--")
plt.xlabel("Residual (Actual − Predicted)")
plt.ylabel("Count")
plt.title("Residual Distribution")
plt.tight_layout()
plt.savefig("outputs/evaluation/residuals.png", dpi=150)
plt.close()

print("\nAll evaluation outputs saved in outputs/evaluation/")
print("Best model saved  → models/best_ann_model.pt")



